Add realtime
donkey-engine/donkey-engine pull request #97
Opened 2021-07-03 18:01 UTC by BehindLoader

2021-07-11 18:06 UTC, tmcgroul commented on common/clients/ws.py
> +        print(response.text)
а это легально?

2021-07-11 18:06 UTC, BehindLoader commented on common/clients/ws.py
> +        print(response.text)
оййййййййййй. сори. щщас поправлю

2021-07-11 18:33 UTC, tmcgroul approved these changes, later dismissed

2021-07-16 11:29 UTC, lroskoshin commented on common/clients/ws.py
> +REDIS_USER_ROOM_KEY = 'ws:{user_id}'
А будет ли данный темплейт ещё где-то использоваться, может тогда сделать через интерполяцию сразу в нужном месте https://www.python.org/dev/peps/pep-0498/ .  Как на мой взгляд это классно, потому что ты сразу видишь куда и что вставляется в месте использования. Часто когда видешь 'string'.format(), приходится потом лезть что бы понять, а если действительно вообще важная инфа, то можем сделать функцией, которая принимает id, так ты абстрогируешься от знания что есть какая-то строка и она как то форматится

2021-07-19 20:00 UTC, tmcgroul approved these changes

2021-07-19 20:35 UTC, tmcgroul commented
в requirements не указана либа для редиса

2021-07-19 20:36 UTC, tmcgroul requested changes
в requirements нет редиса

2021-07-19 20:37 UTC, tmcgroul approved these changes

2021-07-19 20:38 UTC, tmcgroul commented
> в requirements нет редиса
всё есть
зря быканул

2021-08-24 18:07 UTC, merged